from typing import List
from app.domain.value_objects import FormField


class BrowserAutomation:
    """Interface for browser automation tasks."""

    def open(self, url: str) -> None: ...
    def page_contains(self, text: str) -> bool: ...
    def get_form_fields(self) -> List[FormField]: ...
    def fill_field(self, field: FormField, value: str) -> None: ...
    def submit(self) -> None: ...
    def close(self) -> None: ...
